[package]
name = "mirrorshine"
version = "0.1.0"
edition = "2021"
description = "Rsync based mirror administration cli"
[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.5"
